# Generated by Django 5.0.3 on 2024-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_input', '0002_alter_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
